name: Deploy to Production

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build artifact
        steps:
            - uses: actions/checkout@v2
              name: Checkout

            - name: Installing dependencies
              run: npm ci

            - name: Build project
              run: npm run build
